### ISSUE TITLE
video4linux video0: frame start syncpt timeout!0

### ISSUE THREAD

**Issue by tuyaliang** [gvsyn/jetson_tc358743#1]
Hello:
 I port it to jetson nano b01,but I have some error:

[  323.493774] tc358743 7-000f: -----CSI-TX status-----
[  323.493777] tc358743 7-000f: Lanes needed: 2
[  323.494083] tc358743 7-000f: Lanes in use: 2
[  323.494349] tc358743 7-000f: Waiting for particular sync signal: no
[  323.494709] tc358743 7-000f: Transmit mode: no
[  323.494975] tc358743 7-000f: Receive mode: no
[  323.495234] tc358743 7-000f: Stopped: no
[  323.495237] tc358743 7-000f: Color space: YCbCr 422 16-bit
[  323.495471] tc358743 7-000f: -----HDMI status-----
[  323.495474] tc358743 7-000f: HDCP encrypted content: no
[  323.495477] tc358743 7-000f: Input color space: RGB limited range
[  323.495711] tc358743 7-000f: AV Mute: off
[  323.495945] tc358743 7-000f: Deep color mode: 8-bits per channel
[  323.496866] tc358743 7-000f: HDMI infoframe: Auxiliary Video Information (AVI), version 2, length 13
[  323.496870] tc358743 7-000f:     colorspace: RGB
[  323.496873] tc358743 7-000f:     scan mode: Underscan
[  323.496876] tc358743 7-000f:     colorimetry: ITU709
[  323.496879] tc358743 7-000f:     picture aspect: 16:9
[  323.496882] tc358743 7-000f:     active aspect: Same as Picture
[  323.496885] tc358743 7-000f:     itc: No Data
[  323.496888] tc358743 7-000f:     extended colorimetry: xvYCC 601
[  323.496891] tc358743 7-000f:     quantization range: Default
[  323.496894] tc358743 7-000f:     nups: Unknown Non-uniform Scaling
[  323.496897] tc358743 7-000f:     video code: 31
[  323.496899] tc358743 7-000f:     ycc quantization range: Limited
[  323.496902] tc358743 7-000f:     hdmi content type: Graphics
[  323.496905] tc358743 7-000f:     pixel repeat: 0
[  323.496908] tc358743 7-000f:     bar top 0, bottom 0, left 0, right 0
[  323.698550] video4linux video0: frame start syncpt timeout!0
[  323.906586] video4linux video0: frame start syncpt timeout!0
[  324.114514] video4linux video0: frame start syncpt timeout!0
[  324.322544] video4linux video0: frame start syncpt timeout!0
[  324.530525] video4linux video0: frame start syncpt timeout!0
[  324.738521] video4linux video0: frame start syncpt timeout!0
[  324.946507] video4linux video0: frame start syncpt timeout!0
[  325.154480] video4linux video0: frame start syncpt timeout!0
[  325.362472] video4linux video0: frame start syncpt timeout!0
[  325.570446] video4linux video0: frame start syncpt timeout!0
[  325.778436] video4linux video0: frame start syncpt timeout!0
[  325.986421] video4linux video0: frame start syncpt timeout!0
[  326.194400] video4linux video0: frame start syncpt timeout!0
[  326.402377] video4linux video0: frame start syncpt timeout!0
[  326.610367] video4linux video0: frame start syncpt timeout!0
[  326.818339] video4linux video0: frame start syncpt timeout!0
[  327.026334] video4linux video0: frame start syncpt timeout!0
[  327.032135] tc358743 7-000f: Calling tc358743_s_stream
[  327.032138] tc358743 7-000f: enable_stream: disable
[  327.032844] tc358743 7-000f: 786:enable_stream: end

**Comment by tuyaliang** [comment]
I use gst command to show the video:
 gst-launch-1.0 -v --gst-debug-level=1 v4l2src device=/dev/video0 ! "video/x-raw,width=1920,height=1080,format=(string)UYVY" ! nvvidconv ! "video/x-raw(memory:NVMM),width=1920,height=1080,format=(string)I420" ! nvoverlaysink sync=false

**Comment by tuyaliang** [comment]
I use Auvidea b101 board.

**Comment by gvsyn** [comment]
What device was plugged into the HDMI port? Was the device on?

**Comment by gvsyn** [comment]
@tuyaliang any update?

**Comment by tuyaliang** [comment]
> 

Thanks, I changed another b01 borad, and it worked, it maybe hardware problem.

**Comment by tuyaliang** [comment]
https://www.bilibili.com/video/BV1KY4y137oi?spm_id_from=333.999.0.0

**Comment by gvsyn** [comment]
Ok, closing the issue. Good to see it running
